export const GET_RESEARCHERS_REQUEST = "GET_RESEARCHERS_REQUEST",
  GET_RESEARCHERS_SUCCESS = "GET_RESEARCHERS_SUCCESS",
  GET_RESEARCHERS_FAILURE = "GET_RESEARCHERS_FAILURE",
  GET_ADMIN_RECORDS_REQUEST = "GET_ADMIN_RECORDS_REQUEST",
  GET_ADMIN_RECORDS_SUCCESS = "GET_ADMIN_RECORDS_SUCCESS",
  GET_ADMIN_RECORDS_FAILURE = "GET_ADMIN_RECORDS_FAILURE";
