export const FETCH_ALL_RECORDS_REQUEST = 'FETCH_ALL_RECORDS_REQUEST',
  FETCH_ALL_RECORDS_SUCCESS = 'FETCH_ALL_RECORDS_SUCCESS',
  FETCH_ALL_RECORDS_FAILURE = 'FETCH_ALL_RECORDS_FAILURE',
  FETCH_USER_RECORDS_REQUEST = 'FETCH_USER_RECORDS_REQUEST',
  FETCH_USER_RECORDS_SUCCESS = 'FETCH_USER_RECORDS_SUCCESS',
  FETCH_USER_RECORDS_FAILURE = 'FETCH_USER_RECORDS_FAILURE';
