export const GET_DIVERSITY_REQUEST = "GET_DIVERSITY_REQUEST",
  GET_DIVERSITY_SUCCESS = "GET_DIVERSITY_SUCCESS",
  GET_DIVERSITY_FAILURE = "GET_DIVERSITY_FAILURE",
  GET_OBJECT_PATH_REQUEST = "GET_OBJECT_PATH_REQUEST",
  GET_OBJECT_PATH_SUCCESS = "GET_OBJECT_PATH_SUCCESS",
  GET_OBJECT_PATH_FAILURE = "GET_OBJECT_PATH_FAILURE";
